// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("JsonWrapperPlugin.Tests")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.JsonWrapper")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-05-26T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","0fdc94a755c30872e1abfef64fb1a08503abe96e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "JsonWrapperPlugin.Tests"
    let [<Literal>] AssemblyProduct = "BinaryDefense.JsonWrapper"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-05-26T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "0fdc94a755c30872e1abfef64fb1a08503abe96e"
