// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BinaryDefense.Myriad.Plugins.JsonWrapper")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.JsonWrapper")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-06-05T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","aac89b8ca30516e1131edf059e62fd7835311da4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BinaryDefense.Myriad.Plugins.JsonWrapper"
    let [<Literal>] AssemblyProduct = "BinaryDefense.JsonWrapper"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-06-05T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "aac89b8ca30516e1131edf059e62fd7835311da4"
