// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BinaryDefense.JsonWrapper.Core")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.JsonWrapper")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-05-27T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","dc13033f83b3f14f5d63728abf3c65a15db93cc4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BinaryDefense.JsonWrapper.Core"
    let [<Literal>] AssemblyProduct = "BinaryDefense.JsonWrapper"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-05-27T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "dc13033f83b3f14f5d63728abf3c65a15db93cc4"
